version: '3.8'

services:
  api:
    image: rest-orders-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=YourDatabaseName;User=sa;Password=Y0urStr0ngPassw0rd1!;
    networks:
      - rest-orders-net

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      SA_PASSWORD: "Y0urStr0ngPassw0rd1!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_DATA_DIR: "/var/opt/mssql/data"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql/data
    networks:
      - rest-orders-net

networks:
  rest-orders-net:

volumes:
  db-data: